### ISSUE TITLE
Expose error message from convert_fastaqual_fastq.py 

### ISSUE THREAD

**Issue by ElDeveloper** [qiita-spots/qtp-target-gene#21]
In [this block](https://github.com/qiita-spots/qp-target-gene/blob/0ff10bc111e32cad709aad2b070baeea946154df/qp_target_gene/split_libraries/split_libraries.py#L267-L271), the error message is not exposed to the and instead a generic message is shown "Error converting the fasta/qual files to fastq".

While trying to help a Qiita user, we couldn't figure out why their processing was failing, so I ended up running the command directly on the command line.

**Comment by antgonza** [comment]
Note that the issue is in qp-target-gene and not here (qtp-target-gene); anyway, fix: https://github.com/qiita-spots/qp-target-gene/pull/17

**Comment by ElDeveloper** [comment]
My bad, thanks for fixing 👍
