### ISSUE TITLE
Update sequence HTML summary to use QIIME2's interactive plots

### ISSUE THREAD

**Issue by ElDeveloper** [qiita-spots/qtp-target-gene#35]
The sequence summary for demultiplexed sequence artifacts is fairly minimal and mostly shows information about the length of the sequences.

<img width="736" alt="Screen Shot 2021-03-22 at 2 11 04 PM" src="https://user-images.githubusercontent.com/375307/112058956-7a2a4a80-8b18-11eb-82f4-ce23bd337fbf.png">

It would be nice if this could be replaced by something like QIIME2's [sequence summary view](https://view.qiime2.org/?src=https%3A%2F%2Fdocs.qiime2.org%2F2021.2%2Fdata%2Ftutorials%2Fmoving-pictures%2Fdemux.qzv). This artifact includes information about the quality scores per position:

<img width="1553" alt="Screen Shot 2021-03-22 at 2 13 46 PM" src="https://user-images.githubusercontent.com/375307/112059277-e147ff00-8b18-11eb-933e-957155b3db51.png">

-----------------

This issue really goes in the data type plugin (validate/summarize) here: https://github.com/qiita-spots/qtp-sequencing/; could you move it? ... and I think we could simply reuse: https://github.com/qiime2/q2-demux/blob/master/q2_demux/_summarize/_visualizer.py#L95.

**Comment by antgonza** [comment]
This can be closed here as the issue was moved to another repo and we now have: https://github.com/qiita-spots/qtp-sequencing/pull/41
